name: Health Check
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run health check
        run: echo "Running health check..."
